# Generated by Django 4.2.19 on 2025-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensoredWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='Запрещённое слово')),
            ],
            options={
                'verbose_name': 'Цензурное слово',
                'verbose_name_plural': 'Цензурные слова',
            },
        ),
    ]
