# Generated by Django 4.2.19 on 2025-03-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_censoredword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censoredword',
            options={'verbose_name': '*** слово', 'verbose_name_plural': '*** слова'},
        ),
    ]
