# Generated by Django 4.2.19 on 2025-03-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_censoredword_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Трудный')], default='medium', max_length=20, verbose_name='Сложность'),
        ),
    ]
