# Generated by Django 4.2.19 on 2025-03-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_quizquestions_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'verbose_name': 'Игровая сессия квиза', 'verbose_name_plural': 'Игровые сессии квизов'},
        ),
    ]
