# Generated by Django 4.2.19 on 2025-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gamesession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censoredword',
            options={'verbose_name': 'Цензурное слово', 'verbose_name_plural': 'Цензурные слова'},
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='Правильных ответов'),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='total_answers',
            field=models.IntegerField(default=0, verbose_name='Всего ответов'),
        ),
    ]
