# Generated by Django 4.2.19 on 2025-04-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_censoredword_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='username',
        ),
    ]
