# Generated by Django 4.2.19 on 2025-04-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_leaderboard_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='difficulty',
        ),
    ]
