# Generated by Django 4.2.19 on 2025-03-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('quiz_start', 'Начало квиза'), ('quiz_answer', 'Ответ на вопрос'), ('quiz_answer_correct', 'Правильный ответ'), ('quiz_answer_wrong', 'Неправильный ответ'), ('game_play', 'Запуск игры'), ('location_request', 'Запрос геолокации'), ('faq_open', 'Открытие FAQ'), ('quiz_history_view', 'Просмотр истории квиза'), ('leaderboard_view', 'Просмотр таблицы лидеров')], max_length=100),
        ),
    ]
