# Generated by Django 4.2.19 on 2025-03-27 07:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useractivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='answered_questions_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None, verbose_name='ID вопросов, на которые пользователь уже ответил'),
        ),
    ]
