# Generated by Django 4.2.19 on 2025-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegramuser_answered_questions_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Телеграм пользователь', 'verbose_name_plural': 'Телеграм пользователи'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'Активность пользователя', 'verbose_name_plural': 'Активности пользователей'},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('quiz_start', 'Запуск квиза'), ('game_start', 'Запуск игры'), ('location_request', 'Запрос геолокации'), ('faq_open', 'Открытие FAQ')], max_length=100),
        ),
    ]
