# Generated by Django 4.2.19 on 2025-03-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок совета')),
                ('description', models.TextField(verbose_name='Ответ на вопрос')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advices/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ru', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория отходов',
                'verbose_name_plural': 'Категории отходов',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('title', models.CharField(max_length=255, verbose_name='Название точки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('restricted', models.BooleanField(default=False, verbose_name='Ограниченный доступ')),
                ('categories', models.CharField(blank=True, max_length=100, null=True)),
                ('businesHoursState', models.JSONField(blank=True, null=True, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
            },
        ),
    ]
