# Generated by Django 4.2.19 on 2025-03-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='text',
        ),
    ]
