# Generated by Django 4.2.19 on 2025-03-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_advice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
