# Generated by Django 4.2.19 on 2025-03-11 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_telegramuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='user_id',
            new_name='telegram_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
