# Generated by Django 4.2.19 on 2025-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='advicecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение не должно превышать 80x91px.', null=True, upload_to='advices/', verbose_name='Фото'),
        ),
    ]
