# Generated by Django 4.2.19 on 2025-03-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_requests_count',
            field=models.IntegerField(default=0),
        ),
    ]
