# Generated by Django 4.2.19 on 2025-03-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortinggamesession',
            options={'verbose_name': 'Сортировочная игра', 'verbose_name_plural': 'Сортировочные игры'},
        ),
    ]
