# Generated by Django 4.2.19 on 2025-03-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_advice'),
        ('sorting_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortinggamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='api.telegramuser'),
        ),
    ]
