# Generated by Django 4.2.19 on 2025-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_game', '0002_alter_sortinggamesession_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingGameStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
