# Generated by Django 4.2.19 on 2025-03-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_game', '0003_sortinggamestart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortinggamestart',
            options={'verbose_name_plural': 'Все игры'},
        ),
    ]
