# Generated by Django 4.2.19 on 2025-03-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_game', '0004_alter_sortinggamestart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortinggamesession',
            name='crown',
            field=models.IntegerField(default=0),
        ),
    ]
